apiVersion: v1
kind: Service
metadata:
  name: service1
  labels: {{- include "webchart12.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
  selector:
    {{- include "webchart12.selectorLabels" . | nindent 4 }}
  type: NodePort
