apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scale
spec:
  scaleTargetRef:
    apiVersion:    apps/v1  # Optional. Default: apps/v1
    kind:          Deployment         # Optional. Default: Deployment
    name:          {{ include "webchart12.fullname" . }}          # Mandatory. Must be in the same namespace as the ScaledObject
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 0                                 # Optional. Default: 0
  maxReplicaCount: 100                               # Optional. Default: 100
  triggers:
  - type: cron
    metadata:
    # Required
      timezone: Asia/Jerusalem  # The acceptable values would be a value from the IANA Time Zone Database.
      start: 0 8 * * *
      end: 0 0 * * *
      desiredReplicas: "4"
  - type: cpu
    metadata:
      # Required
      type: Utilization
      value: "60"
  - type: memory
    metadata:
      # Required
      type: Utilization
      value: "70"

